### ISSUE TITLE
username 包含 & ,会验证失败

### ISSUE THREAD

**Issue by sword007** [emqx/emqx-auth-redis#159]
当用户名 包含 & ,用户会登陆不成功。

**Comment by zhanghongtong** [comment]
Hi, @sword007 
Please provide more information, including but not limited to redis version, emqx version, client username, emqx-auth-redis authentication rules, or other information I should know

**Comment by sword007** [comment]
EMQ X Broker, 4.0.7

**Comment by sword007** [comment]
服务器为 unbuntu 18.04 . 
emqx 在控制台中看 是 EMQ X Broker , 4.0.7 这个版本。 
redis 版本为 Redis server  4.0.9。

emqx_auth_redis.conf 内容为
auth.redis.type = single
auth.redis.server = 127.0.0.1:6379
auth.redis.pool = 8
auth.redis.database = 0
auth.redis.auth_cmd = HMGET mqtt_user:%u password
auth.redis.password_hash = plain
auth.redis.super_cmd = HGET mqtt_user:%u is_superuser
#####################################
在 redis 中加入两个用户
HMSET mqtt_user:user&001 password 12345
HMSET mqtt_user:user001 password 12345
用 user001    能够验证通过
用 user&001 不能验证通过

用 mysql 方式验证，没用问题

**Comment by zhanghongtong** [comment]
This is indeed a bug, because erlang's `re:replace/4` function treats `&` as a special character, we will fix this in the next version, thanks for your feedback

**Comment by HJianBo** [comment]
Hi guys, v4.1.0 has released. Plz try it later
