### ISSUE TITLE
 About modifying the permissions of a user who has been connected to an MQTT

### ISSUE THREAD

**Issue by zhaozhenxiang** [emqx/emqx-auth-redis#48]
The scene is as follows:
1. I first set the user: hset mqtt_user: test password test
2. Set the user acl: hset mqtt_acl: test # 3
3. Use mqtt client to connect to the mqtt broker
4. Test the permissions of the client
5. Modify the user's acl: hdel mqtt_acl: test #
6. The user is still able to have permission
7. The user disconnect, and then will find acl is normal.

I do not understand erlang, erlang is not in the connect from the redis Lane access to the authority to load into their own memory, and then the client is not open the situation is not the initiative to get the authority of the client?

I looked at the redis-cli monitor, found that the connection is indeed to check all the permissions.

**Comment by turtleDeng** [comment]
@zhaozhenxiang 
The default publish acl will be cached, and you can modify the configuration to shut down the cache
etc/emq.conf
```
## Cache ACL for PUBLISH
mqtt.cache_acl = true
```
Notice: 
Please do not use Chinese to open issues

**Comment by zhaozhenxiang** [comment]
Thanks.
I am sorry about Chinese.
In the MySQL-auth plugin and mqtt.cache_acl = true, in the send pub and sub data frame emqtt sometimes query tables, I guess is out of the cache.
In the Redis-auth plugin and mqtt.cache_acl = true, in the send pub and sub data frame, I have not seen the query, only in the connect when the query once Redis.
In the Redis-auth plugin and mqtt.cache_acl = false, client in the transmission of ping data frame, emqtt will query Redis.
I think this is not good, I would like to mention a proposal: emqtt exposed a tcp interface, if you want to set up acl, then go directly to the tcp interface and communication, I do not need to know what acl storage medium, I do not need acl cache mechanism.
I finally chose to use Redis-auth and mqtt.cache_acl = false.

**Comment by turtleDeng** [comment]
Thank you for your participation, I will close this issue.
