### ISSUE TITLE
Does the lib support the redis cluster mode?

### ISSUE THREAD

**Issue by travisgu** [emqx/emqx-auth-redis#63]
It seems the eredis lib doesn't support the redis cluster mode. 
Is there a plan to support the cluster mode?

**Comment by emqplus** [comment]
@travisgu This feature will be planned in EMQ R3.0 release.

**Comment by juris** [comment]
any updates on this one?

**Comment by turtleDeng** [comment]
Thank you for your participation, already supported in v3.0, please download the latest version to use.
