### ISSUE TITLE
Is there a way of clearing cache for a hash when a new acl gets added for a user.

### ISSUE THREAD

**Issue by Poly92** [emqx/emqx-auth-redis#72]
I am using emqttd with redis for auth. 

The flow is as follows:
When subscribing for a topic, client sends a list of topics and we return a username/password pair which the client then uses to establish a connection to subscribe and listen to messages. 
Before returning the creds, we make the acl entries for the user for all the passed channels with value 2.
The issue now is that, sometimes due to application architecture we are not aware of or we do not want to subscribe to all the channels and want to do some at a time.
But because of caching, the integration breaks. 
Is there a way to trigger cache refresh when the acl changes for a user.

**Comment by Poly92** [comment]
@emqplus any help?

**Comment by terry-xiaoyu** [comment]
@Poly92 EMQ X 3.0 support expiry interval for the ACL cache. But there's no way do clear ACL cache in EMQ 2.x other than disconnect you client and connect again.

**Comment by turtleDeng** [comment]
Thank you for your participation, we will close this issue.
